on:
  schedule:
    - cron: "0 0 * * 0" # runs every Sunday at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: r-cmd-check

jobs:
  r-cmd-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'devel'}
          - {os: ubuntu-latest,   r: 'release'}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: actions/cache@v3
        with:
          path: ~/.cache/R/renv
          key: ${{ runner.os }}-r-${{ steps.setup.outputs.installed-r-version }}-lock-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-r-${{ steps.setup.outputs.installed-r-version }}-lock-

      - uses: mlr-org/actions/renv-system-dependencies@v1
        with:
          path: "renv.lock"

      - name: Restore renv environment
        run: |
          R -q -e 'options(Ncpus = 2); install.packages("renv", repos = "cloud.r-project.org"); renv::restore()'

      - uses: r-lib/actions/check-r-package@v2
